# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/img/app_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuEdit_Geometry = QtWidgets.QMenu(self.menuEdit)
        self.menuEdit_Geometry.setObjectName("menuEdit_Geometry")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.actio_open_geometry = QtWidgets.QAction(MainWindow)
        self.actio_open_geometry.setObjectName("actio_open_geometry")
        self.action_reload = QtWidgets.QAction(MainWindow)
        self.action_reload.setObjectName("action_reload")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_edit_signal = QtWidgets.QAction(MainWindow)
        self.action_edit_signal.setObjectName("action_edit_signal")
        self.actionEdit_Road = QtWidgets.QAction(MainWindow)
        self.actionEdit_Road.setObjectName("actionEdit_Road")
        self.actionEdit_Ped = QtWidgets.QAction(MainWindow)
        self.actionEdit_Ped.setObjectName("actionEdit_Ped")
        self.actionEdit_Ped_Crossing = QtWidgets.QAction(MainWindow)
        self.actionEdit_Ped_Crossing.setObjectName("actionEdit_Ped_Crossing")
        self.actionEdit_Sep_Island = QtWidgets.QAction(MainWindow)
        self.actionEdit_Sep_Island.setObjectName("actionEdit_Sep_Island")
        self.action_toggle_dark_mode = QtWidgets.QAction(MainWindow)
        self.action_toggle_dark_mode.setObjectName("action_toggle_dark_mode")
        self.actio_save = QtWidgets.QAction(MainWindow)
        self.actio_save.setObjectName("actio_save")
        self.action_save_geometry = QtWidgets.QAction(MainWindow)
        self.action_save_geometry.setObjectName("action_save_geometry")
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_edit_agents = QtWidgets.QAction(MainWindow)
        self.action_edit_agents.setObjectName("action_edit_agents")
        self.action_edit_simulation = QtWidgets.QAction(MainWindow)
        self.action_edit_simulation.setObjectName("action_edit_simulation")
        self.action_road = QtWidgets.QAction(MainWindow)
        self.action_road.setObjectName("action_road")
        self.action_ped_boundary = QtWidgets.QAction(MainWindow)
        self.action_ped_boundary.setObjectName("action_ped_boundary")
        self.action_bike_boundary = QtWidgets.QAction(MainWindow)
        self.action_bike_boundary.setObjectName("action_bike_boundary")
        self.menuFile.addAction(self.action_new)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.actio_save)
        self.menuFile.addAction(self.action_close)
        self.menuFile.addAction(self.action_reload)
        self.menuSetting.addAction(self.action_toggle_dark_mode)
        self.menuEdit_Geometry.addAction(self.action_road)
        self.menuEdit_Geometry.addAction(self.action_ped_boundary)
        self.menuEdit_Geometry.addAction(self.action_bike_boundary)
        self.menuEdit.addAction(self.action_edit_signal)
        self.menuEdit.addAction(self.action_edit_agents)
        self.menuEdit.addAction(self.action_edit_simulation)
        self.menuEdit.addAction(self.menuEdit_Geometry.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PedSim"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuEdit_Geometry.setTitle(_translate("MainWindow", "Edit Geometry"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.actio_open_geometry.setText(_translate("MainWindow", "Open Geometry"))
        self.action_reload.setText(_translate("MainWindow", "Reload"))
        self.action_close.setText(_translate("MainWindow", "Close"))
        self.action_edit_signal.setText(_translate("MainWindow", "Edit Signal"))
        self.actionEdit_Road.setText(_translate("MainWindow", "Edit Road"))
        self.actionEdit_Ped.setText(_translate("MainWindow", "Edit Bike Lane"))
        self.actionEdit_Ped_Crossing.setText(_translate("MainWindow", "Edit Ped Crossing"))
        self.actionEdit_Sep_Island.setText(_translate("MainWindow", "Edit Sep Island"))
        self.action_toggle_dark_mode.setText(_translate("MainWindow", "Toggle Dark Mode"))
        self.actio_save.setText(_translate("MainWindow", "Save"))
        self.action_save_geometry.setText(_translate("MainWindow", "Save Geometry"))
        self.action_new.setText(_translate("MainWindow", "New"))
        self.action_edit_agents.setText(_translate("MainWindow", "Edit Agents"))
        self.action_edit_simulation.setText(_translate("MainWindow", "Edit Simulation"))
        self.action_road.setText(_translate("MainWindow", "Road"))
        self.action_ped_boundary.setText(_translate("MainWindow", "Ped Boundary"))
        self.action_bike_boundary.setText(_translate("MainWindow", "Bike Boundary"))
import resource_rc
