# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/ui/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/img/app_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuEdit_Geometry = QtWidgets.QMenu(self.menuEdit)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./resources/ui/../img/geometry.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuEdit_Geometry.setIcon(icon1)
        self.menuEdit_Geometry.setObjectName("menuEdit_Geometry")
        self.menuRoad = QtWidgets.QMenu(self.menuEdit_Geometry)
        self.menuRoad.setObjectName("menuRoad")
        self.menuBoundary = QtWidgets.QMenu(self.menuEdit_Geometry)
        self.menuBoundary.setObjectName("menuBoundary")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuToolbars = QtWidgets.QMenu(self.menuView)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./resources/ui/../img/toolbar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuToolbars.setIcon(icon2)
        self.menuToolbars.setObjectName("menuToolbars")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./resources/ui/../img/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon3)
        self.action_open.setObjectName("action_open")
        self.actio_open_geometry = QtWidgets.QAction(MainWindow)
        self.actio_open_geometry.setObjectName("actio_open_geometry")
        self.action_reload = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./resources/ui/../img/reload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_reload.setIcon(icon4)
        self.action_reload.setObjectName("action_reload")
        self.action_close = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./resources/ui/../img/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_close.setIcon(icon5)
        self.action_close.setObjectName("action_close")
        self.action_edit_signal = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./resources/ui/../img/signal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_edit_signal.setIcon(icon6)
        self.action_edit_signal.setObjectName("action_edit_signal")
        self.actionEdit_Road = QtWidgets.QAction(MainWindow)
        self.actionEdit_Road.setObjectName("actionEdit_Road")
        self.actionEdit_Ped = QtWidgets.QAction(MainWindow)
        self.actionEdit_Ped.setObjectName("actionEdit_Ped")
        self.actionEdit_Ped_Crossing = QtWidgets.QAction(MainWindow)
        self.actionEdit_Ped_Crossing.setObjectName("actionEdit_Ped_Crossing")
        self.actionEdit_Sep_Island = QtWidgets.QAction(MainWindow)
        self.actionEdit_Sep_Island.setObjectName("actionEdit_Sep_Island")
        self.action_toggle_dark_mode = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./resources/ui/../img/dark_mode.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_toggle_dark_mode.setIcon(icon7)
        self.action_toggle_dark_mode.setObjectName("action_toggle_dark_mode")
        self.action_save = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./resources/ui/../img/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_save.setIcon(icon8)
        self.action_save.setObjectName("action_save")
        self.action_save_geometry = QtWidgets.QAction(MainWindow)
        self.action_save_geometry.setObjectName("action_save_geometry")
        self.action_new = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./resources/ui/../img/new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_new.setIcon(icon9)
        self.action_new.setObjectName("action_new")
        self.action_edit_agents = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./resources/ui/../img/agent.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_edit_agents.setIcon(icon10)
        self.action_edit_agents.setObjectName("action_edit_agents")
        self.action_edit_simulation = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("./resources/ui/../img/simulation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_edit_simulation.setIcon(icon11)
        self.action_edit_simulation.setObjectName("action_edit_simulation")
        self.action_bike_boundary = QtWidgets.QAction(MainWindow)
        self.action_bike_boundary.setObjectName("action_bike_boundary")
        self.action_edit_road = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("./resources/ui/../img/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_edit_road.setIcon(icon12)
        self.action_edit_road.setObjectName("action_edit_road")
        self.action_add_road = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("./resources/ui/../img/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_road.setIcon(icon13)
        self.action_add_road.setObjectName("action_add_road")
        self.action_remove_road = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("./resources/ui/../img/remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_remove_road.setIcon(icon14)
        self.action_remove_road.setObjectName("action_remove_road")
        self.action_edit_bound = QtWidgets.QAction(MainWindow)
        self.action_edit_bound.setIcon(icon12)
        self.action_edit_bound.setObjectName("action_edit_bound")
        self.action_add_bound = QtWidgets.QAction(MainWindow)
        self.action_add_bound.setIcon(icon13)
        self.action_add_bound.setObjectName("action_add_bound")
        self.action_remove_bound = QtWidgets.QAction(MainWindow)
        self.action_remove_bound.setIcon(icon14)
        self.action_remove_bound.setObjectName("action_remove_bound")
        self.action_pan = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("./resources/ui/../img/pan.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_pan.setIcon(icon15)
        self.action_pan.setObjectName("action_pan")
        self.action_pointer = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("./resources/ui/../img/pointer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_pointer.setIcon(icon16)
        self.action_pointer.setObjectName("action_pointer")
        self.action_toggle_toolbar_file = QtWidgets.QAction(MainWindow)
        self.action_toggle_toolbar_file.setCheckable(True)
        self.action_toggle_toolbar_file.setChecked(True)
        self.action_toggle_toolbar_file.setObjectName("action_toggle_toolbar_file")
        self.action_toggle_toolbar_edit = QtWidgets.QAction(MainWindow)
        self.action_toggle_toolbar_edit.setCheckable(True)
        self.action_toggle_toolbar_edit.setChecked(True)
        self.action_toggle_toolbar_edit.setObjectName("action_toggle_toolbar_edit")
        self.action_toggle_toolbar_view = QtWidgets.QAction(MainWindow)
        self.action_toggle_toolbar_view.setCheckable(True)
        self.action_toggle_toolbar_view.setChecked(True)
        self.action_toggle_toolbar_view.setObjectName("action_toggle_toolbar_view")
        self.action_toggle_toolbar_settings = QtWidgets.QAction(MainWindow)
        self.action_toggle_toolbar_settings.setCheckable(True)
        self.action_toggle_toolbar_settings.setChecked(True)
        self.action_toggle_toolbar_settings.setObjectName("action_toggle_toolbar_settings")
        self.action_fit = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("./resources/ui/../img/fit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_fit.setIcon(icon17)
        self.action_fit.setObjectName("action_fit")
        self.menuFile.addAction(self.action_new)
        self.menuFile.addAction(self.action_open)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_close)
        self.menuFile.addAction(self.action_reload)
        self.menuSetting.addAction(self.action_toggle_dark_mode)
        self.menuRoad.addAction(self.action_edit_road)
        self.menuRoad.addAction(self.action_add_road)
        self.menuRoad.addAction(self.action_remove_road)
        self.menuBoundary.addAction(self.action_edit_bound)
        self.menuBoundary.addAction(self.action_add_bound)
        self.menuBoundary.addAction(self.action_remove_bound)
        self.menuEdit_Geometry.addAction(self.menuRoad.menuAction())
        self.menuEdit_Geometry.addAction(self.menuBoundary.menuAction())
        self.menuEdit.addAction(self.action_edit_signal)
        self.menuEdit.addAction(self.action_edit_agents)
        self.menuEdit.addAction(self.action_edit_simulation)
        self.menuEdit.addAction(self.menuEdit_Geometry.menuAction())
        self.menuToolbars.addAction(self.action_toggle_toolbar_file)
        self.menuToolbars.addAction(self.action_toggle_toolbar_edit)
        self.menuToolbars.addAction(self.action_toggle_toolbar_view)
        self.menuToolbars.addAction(self.action_toggle_toolbar_settings)
        self.menuView.addAction(self.action_pan)
        self.menuView.addAction(self.action_pointer)
        self.menuView.addAction(self.action_fit)
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PedSim"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuEdit_Geometry.setTitle(_translate("MainWindow", "Edit Geometry"))
        self.menuRoad.setTitle(_translate("MainWindow", "Road"))
        self.menuBoundary.setTitle(_translate("MainWindow", "Boundary"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuToolbars.setTitle(_translate("MainWindow", "Toolbars"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.actio_open_geometry.setText(_translate("MainWindow", "Open Geometry"))
        self.action_reload.setText(_translate("MainWindow", "Reload"))
        self.action_close.setText(_translate("MainWindow", "Close"))
        self.action_edit_signal.setText(_translate("MainWindow", "Edit Signal"))
        self.actionEdit_Road.setText(_translate("MainWindow", "Edit Road"))
        self.actionEdit_Ped.setText(_translate("MainWindow", "Edit Bike Lane"))
        self.actionEdit_Ped_Crossing.setText(_translate("MainWindow", "Edit Ped Crossing"))
        self.actionEdit_Sep_Island.setText(_translate("MainWindow", "Edit Sep Island"))
        self.action_toggle_dark_mode.setText(_translate("MainWindow", "Toggle Dark Mode"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save_geometry.setText(_translate("MainWindow", "Save Geometry"))
        self.action_new.setText(_translate("MainWindow", "New"))
        self.action_edit_agents.setText(_translate("MainWindow", "Edit Agents"))
        self.action_edit_simulation.setText(_translate("MainWindow", "Edit Simulation"))
        self.action_bike_boundary.setText(_translate("MainWindow", "Bike Boundary"))
        self.action_edit_road.setText(_translate("MainWindow", "Edit"))
        self.action_add_road.setText(_translate("MainWindow", "Add"))
        self.action_remove_road.setText(_translate("MainWindow", "Remove"))
        self.action_edit_bound.setText(_translate("MainWindow", "Edit"))
        self.action_add_bound.setText(_translate("MainWindow", "Add"))
        self.action_remove_bound.setText(_translate("MainWindow", "Remove"))
        self.action_pan.setText(_translate("MainWindow", "Pan"))
        self.action_pointer.setText(_translate("MainWindow", "Pointer"))
        self.action_toggle_toolbar_file.setText(_translate("MainWindow", "File"))
        self.action_toggle_toolbar_edit.setText(_translate("MainWindow", "Edit"))
        self.action_toggle_toolbar_view.setText(_translate("MainWindow", "View"))
        self.action_toggle_toolbar_settings.setText(_translate("MainWindow", "Setting"))
        self.action_fit.setText(_translate("MainWindow", "fit"))
import resource_rc
